name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4

    - name: Read node version from Dockerfile
      shell: bash
      run: |
        echo ::group::Read node version from Dockerfile
        echo ::set-output name=value::$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' .devcontainer/Dockerfile)
        echo ::endgroup::
      id: node_version

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.node_version.outputs.value }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: |
        echo ::group::Install dependencies
        pnpm install
        echo ::endgroup::
