name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version }}
          echo ::set-output name=new_version::$(jq -r .version package.json)

      - name: Push
        run: |
          git push origin HEAD:${GITHUB_REF}
          git push origin --tags

      - name: Build
        run: pnpm build

      - name: Copy license file
        run: cp LICENSE.md dist

      - name: Compute archive basename
        id: context
        run: echo ::set-output name=archive_basename::$(jq -r .name package.json)-${{ steps.bump_version.outputs.new_version }}

      - name: Rename directory for archive
        run: mv dist ${{ steps.context.outputs.archive_basename }}

      - name: Make tarball
        uses: TheDoctor0/zip-release@0.6.2
        with:
          path: ${{ steps.context.outputs.archive_basename }}
          type: tar
          filename: ${{ steps.context.outputs.archive_basename }}.tar.gz

      - name: Make zipball
        uses: TheDoctor0/zip-release@0.6.2
        with:
          path: ${{ steps.context.outputs.archive_basename }}
          type: zip
          filename: ${{ steps.context.outputs.archive_basename }}.zip

      - name: Create release draft
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ steps.bump_version.outputs.new_version }}
          tag: ${{ steps.bump_version.outputs.new_version }}
          draft: true
          artifacts: '${{ steps.context.outputs.archive_basename }}.*'
          token: ${{ secrets.GITHUB_TOKEN }}
